Repository IEEE-MAE/IEEE-Mae-SOEN341_Project_W25, pull requests merged in 2025-04, with the labels that each got.

#189 #174 Created user interface to edit messages
  src/TeamPage.css
  src/components/TeamPage.jsx
Labels: frontend, Sprint4

#198 #196 Make default channels more visible
  src/TeamPage.css
  src/backend/Queries/getEffectChannel.jsx
  src/components/TeamPage.jsx
Labels: enhancement, frontend, backend, Sprint4

#201 #200 the chat container now moves when we expand the user list, as well as we display the chat name in a more convinient place
  src/TeamPage.css
  src/components/TeamPage.jsx
Labels: frontend

#208 #202 code standardized part2 fixing as many sonarqube errors as there is possible whithin the time frame
  src/App.css
  src/Style.css
  src/TeamPage.css
  src/assets/Iridescence.jsx
  src/backend/Queries/basicqueryUsers.jsx
  src/backend/Queries/getEffectChannel.jsx
  src/backend/Queries/getEffectMessage.jsx
  src/backend/Queries/getUserFields.jsx
  src/backend/auth.jsx
  src/components/LogIn.jsx
  src/components/TeamPage.jsx
Labels: bug, documentation
